---
title: "QP-6"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(shiny)
library(dplyr)
library(plotly)

data(diamonds)

data <- diamonds
Categorical.Variables = c("cut", "color", "clarity")
Numeric.Variables = c("carat", "depth", "table","price","x","y","z")
```

Page 1
===
Column {data-width=650}
-----------------------------------------------------------------------

### Chart 1.1

```{r}
diamonds %>% 
  ggplot(aes(x = cut, y = mean(price), fill = cut)) +
  geom_bar(stat = "identity") +
  ggtitle("Basic Bar Plot") +
  xlab("CUT") +
  ylab("price") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```


Page 2 
===
Column {data-width=450}
-----------------------------------------------------------------------

### Chart 2.1

```{r}
#Stacked Bar Plot
diamonds %>%
  ggplot(aes(x = cut, fill = clarity)) + # removed y argument and value
  geom_bar() +
  ggtitle("Stacked Bar Plot") +
  xlab("CUT") +
  ylab("COUNT") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```

### Chart 2.2

```{r}
#Grouped Bar Plot
ggplot(data) +
  geom_bar(aes(x = cut, fill = clarity), position = 'dodge') +
  ggtitle("Grouped Bar Plot") +
  xlab("CUT") +
  ylab("COUNT") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```


Page 3
===
Column {data-width=450}
-----------------------------------------------------------------------

### Chart 3.1

```{r}
#tiles plot
ggplot(as.data.frame(table(data$cut,
                           data$color))) +
  geom_tile(aes(x = Var1, y = Var2, fill = Freq)) +
  geom_text(aes(x = Var1, y = Var2, label = Freq),
            color = "yellow") +
  ggtitle("Tiles Plot") +
  xlab("CUT") +
  ylab("COLOR") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart 3.2

```{r}
#Ridge Plot
library(ggridges)
ggplot(data) +
  geom_density_ridges(aes(x = carat , y = cut,
                          fill = clarity), alpha = 0.7) +
  ggtitle("Ridge Plot") +
  xlab("carat") +
  ylab("CUT") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```

### Chart 3.3
```{r}
#violin plot
ggplot(diamonds) +
  geom_violin(aes(x = cut , y = carat, fill = cut)) +
  ggtitle("Violin Plot") +
  xlab("CUT") +
  ylab("CARAT") +
  theme_bw() +
  
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```


Page 4
===
Column {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r}
selectInput("categorical_variable", label = "Select Categorical Variable:", choices = Categorical.Variables)

selectInput("numeric_variable", label = "Select Numeric Variable:", choices = Numeric.Variables)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart 4.1

```{r}
renderPlotly({
   plot_ly(data,
              x = ~data[[input$numeric_variable]],
              color = ~data[[input$categorical_variable]],
              colors = "Paired",
              type = "box") %>%
  layout(title = "",
         xaxis = list(title = "" ,
                      zeroline = FALSE))
})
```


Column {data-width=400}
-----------------------------------------------------------------------

### Chart 4.2

```{r}
renderPlotly({
  data %>%
    count(var = data[[input$categorical_variable]], name = "count") %>%
    plot_ly( x = ~var, y = ~ count, type = "bar", marker = list(color = '#008ae6',
                           line = list(color = '#008ae6', width = 2)), hoverinfo = "x+y") %>%
    add_text(text = ~paste0( " (",   scales::percent(count/sum(count)),")"), 
           textposition = "bottom", 
           textfont = list(size = 12, color = "white"), 
           showlegend = FALSE) %>%
    layout(xaxis = list(title = ""), yaxis = list(title = ""))
})
```

### Chart 4.3

```{r}
renderPlotly({
  plot_ly(x = data[[input$numeric_variable]], type = "histogram",  marker = list(color = "#008ae6",
                            line = list(color = "darkgray",
                                        width = 1)))
})
```



Page 5 {data-icon="fa-hashtag"}
===
Column {.tabset}
-----------------------------------------------------------------------

### Chart 5.1

```{r}
#histogram
#binwidth will decide the number of bands/bins
ggplot(data) +
  geom_histogram(aes(x = price), fill = 'blue',
                 color = "lightblue", binwidth = 500)+
  ggtitle("Basic Histogram") +
  xlab("PRICE") +
  ylab("Frequency") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```

### Chart 5.2

```{r}
#stacked histogram
ggplot(data) +
  geom_histogram(aes(x = price, fill = cut),
                 color = "lightblue", binwidth = 500)+
  ggtitle("Stacked Histogram") +
  xlab("PRICE") +
  ylab("Frequency") +
  theme_bw() +
  theme(axis.text.x = element_text(face = 'bold', size = 10),
        axis.text.y = element_text(face = 'bold', size = 10))
```
